### ISSUE TITLE
Remove roundf()

### ISSUE THREAD

**Issue by MobileMon** [shkutkov/SMVerticalSegmentedControl#2]
if you dont it can do funky things with the segmente sizing

Not sure why this is in the their in the first place

change:
//CGFloat stringHeight = roundf([self getTextHeight:titleString]);
        CGFloat stringHeight = [self getTextHeight:titleString];

and:
//self.segmentHeight = roundf(self.segmentHeight);
        self.segmentHeight = self.segmentHeight;

**Comment by shkutkov** [comment]
@MobileMon I've removed roundf call. I have no idea why I did this about two years ago :)
